name: Check simple unit tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  simple-unit-tests:
    runs-on: self-hosted  # Ensures it runs on your self-hosted runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew --no-daemon jar

      - name: Run GoogleWalletHandler tests
        run: ./gradlew --no-daemon test --tests 'eu.eduTap.core.card.google.GoogleWalletHandlerTest'
