name: Check simple unit tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  google-wallet-handler-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run GoogleWalletHandler tests
        run: ./gradlew test --tests 'eu.eduTap.core.card.google.GoogleWalletHandlerTest'
